baseURL = "https://blog.brycethomsen.com/"
languageCode = "en-us"
title = "bryce thomsen"
theme = "hemingway"
copyright = "&copy; bryce thomsen"
disqusShortname = "blogbryce"
#googleAnalytics = ""

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "bash", "python"]

[[params.social]]
url = "https://github.com/brycethomsen"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/brycethomsen"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.social]]
url = "mailto:hello@brycethomsen.com"
fa_icon = "fa-envelope"
